import type { Flow, Step, CrossFlowDep, GeneratorConfig } from "../types";
import type { JwtAnalysis } from "../jwt_analyzer";

export function renderJest(flows: Flow[], config: GeneratorConfig): string {
  const allCrossFlowDeps = flows.flatMap(f => f.crossFlowDeps ?? []);
  const hasCrossFlow = allCrossFlowDeps.length > 0;

  const lines: string[] = [
    "// Generated by Harmantic",
    `const BASE_URL = "${config.baseUrl}";`,
    "",
  ];

  if (flows.some(f => f.requiresAuth)) {
    lines.push(
      "async function getAuthToken(): Promise<string> {",
      "  // TODO: configure auth",
      "  throw new Error('auth not configured');",
      "}",
      "",
    );
  }

  const jwtAnalyses = config.jwtAnalyses ?? [];
  const hasJwt = jwtAnalyses.length > 0;

  if (hasCrossFlow || hasJwt) {
    lines.push(
      "// Shared state populated by producing tests, consumed by dependent tests",
      "// Tests must run in order (default Jest behaviour with --runInBand)",
      "const sessionState: Record<string, string | undefined> = {};",
      "",
    );
  }

  if (hasJwt) {
    lines.push(
      "function decodeJwt(token: string): Record<string, string> {",
      "  const payload = token.split('.')[1].replace(/-/g, '+').replace(/_/g, '/');",
      "  return JSON.parse(atob(payload));",
      "}",
      "",
    );
  }

  for (let i = 0; i < flows.length; i++) {
    lines.push(...renderFlow(flows[i], i, flows, jwtAnalyses));
    lines.push("");
  }

  return lines.join("\n");
}

function renderFlow(flow: Flow, flowIndex: number, allFlows: Flow[], jwtAnalyses: JwtAnalysis[]): string[] {
  const consumes = flow.crossFlowDeps ?? [];
  const produces = allFlows.flatMap(f => f.crossFlowDeps ?? []).filter(d => d.producedByFlow === flowIndex);

  const lines: string[] = [];

  if (consumes.length > 0) {
    const prereqs = [...new Set(consumes.map(d => allFlows[d.producedByFlow].name))];
    lines.push(`// Requires: ${prereqs.join(", ")}`);
  }

  lines.push(`test("${flow.name}", async () => {`);

  if (flow.requiresAuth) {
    lines.push("  const authToken = await getAuthToken();");
  }

  // Read cross-flow values
  if (consumes.length > 0) {
    for (const dep of consumes) {
      lines.push(`  const ${dep.stateKey} = sessionState["${dep.stateKey}"]; // from ${allFlows[dep.producedByFlow].name}`);
    }
    lines.push("");
  }

  const allDeps = flow.steps.flatMap(s => s.dependencies);

  for (const step of flow.steps) {
    const entry = step.entry;
    const method = entry.request.method.toUpperCase();
    const varName = `response${step.index}`;

    const headers: Record<string, string> = {};
    for (const h of entry.request.headers) {
      const n = h.name.toLowerCase();
      if (n === "content-type" || n === "accept") headers[h.name] = h.value;
    }
    if (flow.requiresAuth) headers["Authorization"] = "Bearer ${authToken}";

    const urlPath = buildUrl(entry.request.url, step, consumes);
    const urlStr = `\`\${BASE_URL}${urlPath}\``;

    const fetchOpts: string[] = [`method: "${method}"`];
    if (Object.keys(headers).length > 0) fetchOpts.push(`headers: ${JSON.stringify(headers)}`);
    if (entry.request.postData?.text) fetchOpts.push(`body: \`${entry.request.postData.text}\``);

    lines.push(`  const ${varName} = await fetch(${urlStr}, { ${fetchOpts.join(", ")} });`);
    lines.push(`  expect(${varName}.status).toBe(${entry.response.status});`);

    // Within-flow extractions
    for (const dep of allDeps.filter(d => d.sourceStepIndex === step.index)) {
      if (dep.extractedFrom === "header.Location") {
        lines.push(`  const ${dep.variableName} = ${varName}.headers.get("Location")!.split("/").pop()!;`);
      } else {
        const path = dep.extractedFrom.replace(/^body\./, "");
        lines.push(`  const body${step.index} = await ${varName}.json();`);
        lines.push(`  const ${dep.variableName} = body${step.index}["${path}"];`);
      }
    }

    // Write cross-flow values to sessionState
    for (const xdep of produces.filter(d => d.producedByStep === step.index)) {
      if (xdep.extractedFrom === "header.Location") {
        lines.push(`  sessionState["${xdep.stateKey}"] = ${varName}.headers.get("Location")!.split("/").pop()!;`);
      } else if (xdep.extractedFrom.startsWith("jwt.")) {
        // emitted in JWT block below
      } else {
        const path = xdep.extractedFrom.replace(/^body\./, "");
        lines.push(`  const xbody${step.index} = await ${varName}.json();`);
        lines.push(`  sessionState["${xdep.stateKey}"] = xbody${step.index}["${path}"];`);
      }
    }

    // JWT decode + claim extraction
    const jwtHere = jwtAnalyses.filter(j => j.flowIndex === flowIndex && j.stepIndex === step.index);
    for (const jwt of jwtHere) {
      lines.push(`  const _token${step.index} = (await ${varName}.json())["${jwt.tokenField}"];`);
      lines.push(`  sessionState["${jwt.tokenField}"] = _token${step.index};`);
      lines.push(`  const _claims${step.index} = decodeJwt(_token${step.index});`);
      for (const claim of jwt.claims) {
        lines.push(`  sessionState["${claim.stateKey}"] = _claims${step.index}["${claim.key}"]; // ${claim.key}`);
      }
    }

    lines.push("");
  }

  lines.push("});");
  return lines;
}

function buildUrl(rawUrl: string, step: Step, crossFlowConsumes: CrossFlowDep[]): string {
  let path: string;
  try { path = new URL(rawUrl).pathname + new URL(rawUrl).search; } catch { path = rawUrl; }

  for (const dep of crossFlowConsumes.filter(d => d.consumedByStep === step.index)) {
    const segment = path.split("/").find(p => p.length >= 6 && /[\d\-]/.test(p));
    if (segment) path = path.replace(segment, `\${${dep.stateKey}}`);
  }

  for (const dep of step.dependencies) {
    const segment = path.split("/").find(p => p.length >= 6 && /[\d\-]/.test(p));
    if (segment) path = path.replace(segment, `\${${dep.variableName}}`);
  }

  return path;
}
