import type { Flow, Step, GeneratorConfig } from "../types";

export function renderJest(flows: Flow[], config: GeneratorConfig): string {
  const lines: string[] = [
    "// Generated by Harmantic",
    `const BASE_URL = "${config.baseUrl}";`,
    "",
  ];

  if (flows.some(f => f.requiresAuth)) {
    lines.push(
      "async function getAuthToken(): Promise<string> {",
      "  // TODO: configure auth",
      "  throw new Error('auth not configured');",
      "}",
      "",
    );
  }

  for (const flow of flows) {
    lines.push(...renderFlow(flow));
    lines.push("");
  }

  return lines.join("\n");
}

function renderFlow(flow: Flow): string[] {
  const lines: string[] = [`test("${flow.name}", async () => {`];

  if (flow.requiresAuth) {
    lines.push("  const authToken = await getAuthToken();");
  }

  const allDeps = flow.steps.flatMap(s => s.dependencies);

  for (const step of flow.steps) {
    const entry = step.entry;
    const method = entry.request.method.toUpperCase();
    const varName = `response${step.index}`;

    const headers: Record<string, string> = {};
    for (const h of entry.request.headers) {
      const n = h.name.toLowerCase();
      if (n === "content-type" || n === "accept") headers[h.name] = h.value;
    }
    if (flow.requiresAuth) headers["Authorization"] = "Bearer ${authToken}";

    const urlPath = buildUrl(entry.request.url, step);
    const urlStr = urlPath.includes("${")
      ? `\`\${BASE_URL}${urlPath}\``
      : `\`\${BASE_URL}${urlPath}\``;

    const fetchOpts: string[] = [`method: "${method}"`];
    if (Object.keys(headers).length > 0) fetchOpts.push(`headers: ${JSON.stringify(headers)}`);
    if (entry.request.postData?.text) fetchOpts.push(`body: \`${entry.request.postData.text}\``);

    lines.push(`  const ${varName} = await fetch(${urlStr}, { ${fetchOpts.join(", ")} });`);
    lines.push(`  expect(${varName}.status).toBe(${entry.response.status});`);

    // Extract for downstream steps
    for (const dep of allDeps.filter(d => d.sourceStepIndex === step.index)) {
      if (dep.extractedFrom === "header.Location") {
        lines.push(`  const ${dep.variableName} = ${varName}.headers.get("Location")!.split("/").pop()!;`);
      } else {
        const path = dep.extractedFrom.replace(/^body\./, "");
        lines.push(`  const body${step.index} = await ${varName}.json();`);
        lines.push(`  const ${dep.variableName} = body${step.index}["${path}"];`);
      }
    }

    lines.push("");
  }

  lines.push("});");
  return lines;
}

function buildUrl(rawUrl: string, step: Step): string {
  let path: string;
  try { path = new URL(rawUrl).pathname + new URL(rawUrl).search; } catch { path = rawUrl; }

  for (const dep of step.dependencies) {
    const segment = path.split("/").find(p => p.length >= 6 && /[\d\-]/.test(p));
    if (segment) path = path.replace(segment, `\${${dep.variableName}}`);
  }
  return path;
}
