import type { Flow, Step, GeneratorConfig } from "../types";

export function renderJest(flows: Flow[], config: GeneratorConfig): string {
  const lines: string[] = [
    "// Generated by Harmantic",
    `const BASE_URL = "${config.baseUrl}";`,
    "",
  ];

  const hasAuth = flows.some(f => f.requiresAuth);
  if (hasAuth) {
    lines.push(
      "async function getAuthToken(): Promise<string> {",
      "  // TODO: configure auth",
      "  throw new Error('auth not configured');",
      "}",
      "",
    );
  }

  for (const flow of flows) {
    lines.push(...renderFlow(flow, hasAuth));
    lines.push("");
  }

  return lines.join("\n");
}

function renderFlow(flow: Flow, hasAuth: boolean): string[] {
  const lines: string[] = [
    `test("${flow.name}", async () => {`,
  ];

  if (flow.requiresAuth) {
    lines.push("  const authToken = await getAuthToken();");
  }

  const extracted = new Map<string, string>();

  for (const step of flow.steps) {
    const entry = step.entry;
    const url = stripBase(entry.request.url);
    const method = entry.request.method.toUpperCase();
    const varName = `response${step.index}`;

    const headers: Record<string, string> = {};
    for (const h of entry.request.headers) {
      const n = h.name.toLowerCase();
      if (n === "content-type" || n === "accept") headers[h.name] = h.value;
    }
    if (flow.requiresAuth) headers["Authorization"] = "Bearer ${authToken}";

    const urlExpr = buildUrl(url, step, extracted);
    const fetchOpts: string[] = [`method: "${method}"`];
    if (Object.keys(headers).length > 0) {
      fetchOpts.push(`headers: ${JSON.stringify(headers)}`);
    }
    if (entry.request.postData?.text) {
      fetchOpts.push(`body: ${entry.request.postData.text}`);
    }

    const urlStr = urlExpr.includes("${") ? `\`\${BASE_URL}${urlExpr}\`` : `\`\${BASE_URL}${urlExpr}\``;
    lines.push(`  const ${varName} = await fetch(${urlStr}, { ${fetchOpts.join(", ")} });`);
    lines.push(`  expect(${varName}.status).toBe(${entry.response.status});`);

    // Extract for downstream
    for (const dep of flow.steps.flatMap(s => s.dependencies).filter(d => d.sourceStepIndex === step.index)) {
      if (dep.extractedFrom === "header.Location") {
        lines.push(`  const ${dep.variableName} = ${varName}.headers.get("Location")!.split("/").pop()!;`);
      } else {
        const path = dep.extractedFrom.replace(/^body\./, "");
        lines.push(`  const body${step.index} = await ${varName}.json();`);
        lines.push(`  const ${dep.variableName} = body${step.index}["${path}"];`);
      }
      extracted.set(dep.variableName, dep.variableName);
    }

    lines.push("");
  }

  lines.push("});");
  return lines;
}

function buildUrl(url: string, step: Step, extracted: Map<string, string>): string {
  let result = url;
  for (const dep of step.dependencies) {
    if (dep.extractedFrom !== "header.Location") continue;
    const segment = result.split("/").find(p => p.length >= 6 && /[\d\-]/.test(p));
    if (segment) result = result.replace(segment, `\${${dep.variableName}}`);
  }
  return result;
}

function stripBase(url: string): string {
  try { return new URL(url).pathname + new URL(url).search; } catch { return url; }
}
