import type { Flow, Step, GeneratorConfig } from "../types";

export function renderPytest(flows: Flow[], config: GeneratorConfig): string {
  const lines: string[] = [
    "# Generated by Harmantic",
    "# pip install httpx pytest",
    "",
    "import pytest",
    "import httpx",
    "",
    `BASE_URL = "${config.baseUrl}"`,
    "",
  ];

  const hasAuth = flows.some(f => f.requiresAuth);
  if (hasAuth) {
    lines.push(
      "@pytest.fixture(scope='session')",
      "def auth_token():",
      "    # TODO: configure auth",
      "    pytest.skip('auth not configured')",
      "",
    );
  }

  lines.push(
    "@pytest.fixture(scope='session')",
    "def client():",
    "    with httpx.Client(base_url=BASE_URL) as c:",
    "        yield c",
    "",
  );

  for (const flow of flows) {
    lines.push(...renderFlow(flow));
    lines.push("");
  }

  return lines.join("\n");
}

function renderFlow(flow: Flow): string[] {
  const params = ["client"];
  if (flow.requiresAuth) params.push("auth_token");
  const lines: string[] = [
    `def test_${sanitizeName(flow.name)}(${params.join(", ")}):`,
  ];

  // Track extracted variables
  const extracted = new Map<string, string>(); // varName -> expression

  for (const step of flow.steps) {
    const entry = step.entry;
    const url = stripBase(entry.request.url, "");
    const method = entry.request.method.toLowerCase();
    const varName = `response_${step.index}`;

    // Build headers
    const headers = buildHeaders(entry.request.headers, flow.requiresAuth);

    // Build body
    const body = entry.request.postData?.text
      ? `json=${safeJson(entry.request.postData.text)}`
      : null;

    // Substitute dependency variables into URL
    let urlExpr = buildUrl(url, step, extracted);

    const args = [`"${urlExpr}"`];
    if (headers) args.push(`headers=${headers}`);
    if (body) args.push(body);

    lines.push(`    ${varName} = client.${method}(${args.join(", ")})`);
    lines.push(`    assert ${varName}.status_code == ${entry.response.status}`);

    // Extract values for downstream steps
    for (const dep of flow.steps.flatMap(s => s.dependencies).filter(d => d.sourceStepIndex === step.index)) {
      const extractedVar = dep.variableName;
      if (dep.extractedFrom === "header.Location") {
        lines.push(`    ${extractedVar} = ${varName}.headers["Location"].rstrip("/").rsplit("/", 1)[-1]`);
      } else {
        const jsonPath = dep.extractedFrom.replace(/^body\./, "");
        lines.push(`    ${extractedVar} = ${varName}.json()["${jsonPath}"]`);
      }
      extracted.set(extractedVar, extractedVar);
    }

    lines.push("");
  }

  return lines;
}

function buildUrl(url: string, step: Step, extracted: Map<string, string>): string {
  let result = url;
  for (const dep of step.dependencies) {
    if (dep.extractedFrom !== "header.Location") continue;
    const segment = result.split("/").find(p => p.length >= 6 && /[\d\-]/.test(p));
    if (segment) result = result.replace(segment, `{${dep.variableName}}`);
  }
  // Return as f-string if substitutions were made
  if (result.includes("{")) return `f"${result}"`;
  return result;
}

function buildHeaders(
  headers: Array<{ name: string; value: string }>,
  requiresAuth: boolean
): string | null {
  const keep = headers.filter(h => {
    const n = h.name.toLowerCase();
    return n === "content-type" || n === "accept";
  });
  if (requiresAuth) {
    keep.push({ name: "Authorization", value: "Bearer {auth_token}" });
  }
  if (keep.length === 0) return null;
  const obj = Object.fromEntries(keep.map(h => [h.name, h.value]));
  return JSON.stringify(obj);
}

function safeJson(text: string): string {
  try { JSON.parse(text); return text; } catch { return `"${text.replace(/"/g, '\\"')}"` }
}

function sanitizeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
}

function stripBase(url: string, base: string): string {
  try { return new URL(url).pathname + new URL(url).search; } catch { return url; }
}
