import type { Flow, Step, GeneratorConfig } from "../types";

export function renderPytest(flows: Flow[], config: GeneratorConfig): string {
  const lines: string[] = [
    "# Generated by Harmantic",
    "# pip install httpx pytest",
    "",
    "import pytest",
    "import httpx",
    "",
    `BASE_URL = "${config.baseUrl}"`,
    "",
  ];

  if (flows.some(f => f.requiresAuth)) {
    lines.push(
      "@pytest.fixture(scope='session')",
      "def auth_token():",
      "    # TODO: configure auth",
      "    pytest.skip('auth not configured')",
      "",
    );
  }

  lines.push(
    "@pytest.fixture(scope='session')",
    "def client():",
    "    with httpx.Client(base_url=BASE_URL) as c:",
    "        yield c",
    "",
  );

  for (const flow of flows) {
    lines.push(...renderFlow(flow));
    lines.push("");
  }

  return lines.join("\n");
}

function renderFlow(flow: Flow): string[] {
  const params = ["client"];
  if (flow.requiresAuth) params.push("auth_token");
  const lines: string[] = [
    `def test_${sanitizeName(flow.name)}(${params.join(", ")}):`,
  ];

  // All deps across the flow, keyed by source step
  const allDeps = flow.steps.flatMap(s => s.dependencies);

  for (const step of flow.steps) {
    const entry = step.entry;
    const method = entry.request.method.toLowerCase();
    const varName = `response_${step.index}`;

    const headers = buildHeaders(entry.request.headers, flow.requiresAuth);
    const body = entry.request.postData?.text
      ? `json=${safeJson(entry.request.postData.text)}`
      : null;

    const urlExpr = buildUrl(entry.request.url, step);
    const args = [urlExpr.startsWith("f\"") ? urlExpr : `"${urlExpr}"`];
    if (headers) args.push(`headers=${headers}`);
    if (body) args.push(body);

    lines.push(`    ${varName} = client.${method}(${args.join(", ")})`);
    lines.push(`    assert ${varName}.status_code == ${entry.response.status}`);

    // LLM assertions for this step
    for (const assertion of (flow.llmAssertions ?? [])) {
      if (assertion.includes(varName)) {
        lines.push(`    ${assertion}`);
      }
    }

    // Extract values for downstream steps
    for (const dep of allDeps.filter(d => d.sourceStepIndex === step.index)) {
      if (dep.extractedFrom === "header.Location") {
        lines.push(`    ${dep.variableName} = ${varName}.headers["Location"].rstrip("/").rsplit("/", 1)[-1]`);
      } else {
        const path = dep.extractedFrom.replace(/^body\./, "");
        lines.push(`    ${dep.variableName} = ${varName}.json()["${path}"]`);
      }
    }

    lines.push("");
  }

  return lines;
}

function buildUrl(rawUrl: string, step: Step): string {
  let path: string;
  try { path = new URL(rawUrl).pathname + new URL(rawUrl).search; } catch { path = rawUrl; }

  for (const dep of step.dependencies) {
    const segment = path.split("/").find(p => p.length >= 6 && /[\d\-]/.test(p));
    if (segment) path = path.replace(segment, `{${dep.variableName}}`);
  }
  return path.includes("{") ? `f"${path}"` : path;
}

function buildHeaders(headers: Array<{ name: string; value: string }>, requiresAuth: boolean): string | null {
  const keep = headers.filter(h => {
    const n = h.name.toLowerCase();
    return n === "content-type" || n === "accept";
  });
  if (requiresAuth) keep.push({ name: "Authorization", value: "Bearer {auth_token}" });
  if (keep.length === 0) return null;
  return JSON.stringify(Object.fromEntries(keep.map(h => [h.name, h.value])));
}

function safeJson(text: string): string {
  try { JSON.parse(text); return text; } catch { return JSON.stringify(text); }
}

function sanitizeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
}
