import type { Flow, Step, CrossFlowDep, GeneratorConfig } from "../types";
import type { JwtAnalysis } from "../jwt_analyzer";

export function renderPytest(flows: Flow[], config: GeneratorConfig): string {
  const allCrossFlowDeps = flows.flatMap(f => f.crossFlowDeps ?? []);
  const hasCrossFlow = allCrossFlowDeps.length > 0;
  const jwtAnalyses = config.jwtAnalyses ?? [];
  const hasJwt = jwtAnalyses.length > 0;

  const lines: string[] = [
    "# Generated by Harmantic",
    "# pip install httpx pytest",
    "",
    "import pytest",
    "import httpx",
    "",
    `BASE_URL = "${config.baseUrl}"`,
    "",
  ];

  if (hasJwt) {
    lines.push(
      "def _decode_jwt(token: str) -> dict:",
      "    import base64, json",
      "    payload = token.split('.')[1]",
      "    payload += '=' * (4 - len(payload) % 4)",
      "    return json.loads(base64.b64decode(payload))",
      "",
    );
  }

  if (flows.some(f => f.requiresAuth)) {
    lines.push(
      "@pytest.fixture(scope='session')",
      "def auth_token():",
      "    # TODO: configure auth",
      "    pytest.skip('auth not configured')",
      "",
    );
  }

  lines.push(
    "@pytest.fixture(scope='session')",
    "def client():",
    "    with httpx.Client(base_url=BASE_URL) as c:",
    "        yield c",
    "",
  );

  // session_state dict — shared mutable state across flows
  if (hasCrossFlow) {
    lines.push(
      "@pytest.fixture(scope='session')",
      "def session_state():",
      "    \"\"\"Shared state populated by producing flows, consumed by dependent flows.\"\"\"",
      "    return {}",
      "",
    );
  }

  for (let i = 0; i < flows.length; i++) {
    lines.push(...renderFlow(flows[i], i, flows, hasCrossFlow, jwtAnalyses));
    lines.push("");
  }

  return lines.join("\n");
}

function renderFlow(flow: Flow, flowIndex: number, allFlows: Flow[], hasCrossFlow: boolean, jwtAnalyses: JwtAnalysis[]): string[] {
  const deps = flow.crossFlowDeps ?? [];
  const produces = allFlows.flatMap(f => f.crossFlowDeps ?? []).filter(d => d.producedByFlow === flowIndex);
  const consumes = deps;

  const params = ["client"];
  if (flow.requiresAuth) params.push("auth_token");
  if (hasCrossFlow) params.push("session_state");

  const lines: string[] = [];

  // Comment showing prerequisites
  if (consumes.length > 0) {
    const prereqs = [...new Set(consumes.map(d => `test_${sanitizeName(allFlows[d.producedByFlow].name)}`))];
    lines.push(`# Requires: ${prereqs.join(", ")}`);
  }

  lines.push(`def test_${sanitizeName(flow.name)}(${params.join(", ")}):`);

  // Read cross-flow values from session_state at the top
  if (consumes.length > 0) {
    for (const dep of consumes) {
      lines.push(`    ${dep.stateKey} = session_state["${dep.stateKey}"]  # from test_${sanitizeName(allFlows[dep.producedByFlow].name)}`);
    }
    lines.push("");
  }

  const allDeps = flow.steps.flatMap(s => s.dependencies);

  for (const step of flow.steps) {
    const entry = step.entry;
    const method = entry.request.method.toLowerCase();
    const varName = `response_${step.index}`;

    const headers = buildHeaders(entry.request.headers, flow.requiresAuth);
    const body = entry.request.postData?.text
      ? `json=${safeJson(entry.request.postData.text)}`
      : null;

    const urlExpr = buildUrl(entry.request.url, step, consumes);
    const args = [urlExpr.startsWith("f\"") ? urlExpr : `"${urlExpr}"`];
    if (headers) args.push(`headers=${headers}`);
    if (body) args.push(body);

    lines.push(`    ${varName} = client.${method}(${args.join(", ")})`);
    lines.push(`    assert ${varName}.status_code == ${entry.response.status}`);

    for (const assertion of (flow.llmAssertions ?? [])) {
      if (assertion.includes(varName)) lines.push(`    ${assertion}`);
    }

    // Extract within-flow dependencies
    for (const dep of allDeps.filter(d => d.sourceStepIndex === step.index)) {
      if (dep.extractedFrom === "header.Location") {
        lines.push(`    ${dep.variableName} = ${varName}.headers["Location"].rstrip("/").rsplit("/", 1)[-1]`);
      } else {
        const path = dep.extractedFrom.replace(/^body\./, "");
        lines.push(`    ${dep.variableName} = ${varName}.json()["${path}"]`);
      }
    }

    // Write cross-flow values to session_state
    for (const xdep of produces.filter(d => d.producedByStep === step.index)) {
      if (xdep.extractedFrom === "header.Location") {
        lines.push(`    session_state["${xdep.stateKey}"] = ${varName}.headers["Location"].rstrip("/").rsplit("/", 1)[-1]`);
      } else if (xdep.extractedFrom.startsWith("jwt.")) {
        // JWT claims — emitted below with the token decode block
      } else {
        const path = xdep.extractedFrom.replace(/^body\./, "");
        lines.push(`    session_state["${xdep.stateKey}"] = ${varName}.json()["${path}"]`);
      }
    }

    // JWT token decode + claim extraction
    const jwtHere = jwtAnalyses.filter(j => j.flowIndex === flowIndex && j.stepIndex === step.index);
    for (const jwt of jwtHere) {
      const tokenVar = `_token_${step.index}`;
      const claimsVar = `_claims_${step.index}`;
      lines.push(`    ${tokenVar} = ${varName}.json()["${jwt.tokenField}"]`);
      lines.push(`    session_state["${jwt.tokenField}"] = ${tokenVar}`);
      lines.push(`    ${claimsVar} = _decode_jwt(${tokenVar})`);
      for (const claim of jwt.claims) {
        lines.push(`    session_state["${claim.stateKey}"] = ${claimsVar}.get("${claim.key}")  # ${claim.key}`);
      }
    }

    lines.push("");
  }

  return lines;
}

function buildUrl(rawUrl: string, step: Step, crossFlowConsumes: CrossFlowDep[]): string {
  let path: string;
  try { path = new URL(rawUrl).pathname + new URL(rawUrl).search; } catch { path = rawUrl; }

  // Substitute cross-flow values
  for (const dep of crossFlowConsumes.filter(d => d.consumedByStep === step.index)) {
    const segment = path.split("/").find(p => p.length >= 6 && /[\d\-]/.test(p));
    if (segment) path = path.replace(segment, `{${dep.stateKey}}`);
  }

  // Substitute within-flow values
  for (const dep of step.dependencies) {
    const segment = path.split("/").find(p => p.length >= 6 && /[\d\-]/.test(p));
    if (segment) path = path.replace(segment, `{${dep.variableName}}`);
  }

  return path.includes("{") ? `f"${path}"` : path;
}

function buildHeaders(headers: Array<{ name: string; value: string }>, requiresAuth: boolean): string | null {
  const keep = headers.filter(h => {
    const n = h.name.toLowerCase();
    return n === "content-type" || n === "accept";
  });
  if (requiresAuth) keep.push({ name: "Authorization", value: "Bearer {auth_token}" });
  if (keep.length === 0) return null;
  return JSON.stringify(Object.fromEntries(keep.map(h => [h.name, h.value])));
}

function safeJson(text: string): string {
  try { JSON.parse(text); return text; } catch { return JSON.stringify(text); }
}

function sanitizeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
}
